version: '3.8'

services:
  spring-app:
    image: your_spring_image:latest
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/your_database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - mysql

  angular-app:
    image: your_angular_image:latest
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - spring-app

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword

networks:
  default:
    driver: bridge
