version: '3.3'

services:
  spring-app:
    image: ahmedft1999/image-spring:latest
    container_name: spring-app
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  angular-app:
    image: ahmedft1999/image-spring-front:latest
    container_name: angular-app
    ports:
      - "80:80"
    depends_on:
      - spring-app

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: devops
      MYSQL_USER: devopsuser
      MYSQL_PASSWORD: devopspassword

networks:
  default:
    driver: bridge
